include: "rules/common.smk"
include: "rules/setup.smk"
include: "rules/download.smk"
include: "rules/preprocess.smk"
include: "rules/map.smk"

rule all:
    input:
        expand("/lustre/home/bolner/ENA/data/bam/{u.sample}/{u.unit}.bam.bai", zip, u=units.itertuples())
        #"stats/multiqc/fastp.html"
        #expand("stats/fastp/{u.sample}/{u.unit}_fastp.fastq.gz", zip, u=units.itertuples()),
        #expand("data/split_db/{u.sample}/{u.unit}.tsv",u=units.itertuples()),
        #expand("/lustre/home/bolner/ENA/stats/mosdepth/{u.sample}/{u.unit}.mosdepth.summary.txt", u=units.itertuples())
        #"stats/multiqc/fastp.html",
        #expand("/lustre/home/bolner/ENA/data/bam/{u.sample}/{u.unit}.bam",u=units.itertuples())
